spring.application.name=project_tracker
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=6868

server.servlet.context-path=/project_tracker
#spring.datasource.url=jdbc:postgresql://192.168.0.78:5432/project_tracker_dev
#spring.datasource.username=postgres
#spring.datasource.password=cognine

spring.datasource.url=jdbc:postgresql://103.160.153.30:5432/cognine_dev
spring.datasource.username=cogninedev
spring.datasource.password=cogninedev123$

#spring.datasource.url=jdbc:postgresql://localhost:5432/project_tracker_dev
#spring.datasource.username=postgres
#spring.datasource.password=eswar
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.initialization-mode=always

spring.sql.init.mode=always 

spring.jackson.default-property-inclusion= NON_DEFAULT

#micro-soft

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.windows.net/common/discovery/keys 


#micro-soft mail properties

spring.mail.host = smtp.office365.com
spring.mail.username = tharun.hanmandla@cognine.com
spring.mail.password = daredevil@321
spring.mail.port = 587
spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

hrMail = tharun.hanmandla@cognine.com
pmoMail = sravanthi.gorantla@cognine.com

mailTemplateWithCurrentReportingHead=  <b>{{currentLoginUserName}}</b> Requesting to change reporting head of <b>{{employeeName}}</b> (Employee Id: <b>{{employeeId}}</b>) from <b>{{currentReportingHead}}</b> to <b>{{newReportingHead}}</b>
mailTemplateWithoutCurrentReportingHead=  <b>{{currentLoginUserName}}</b> Requesting to add reporting head of <b>{{employeeName}}</b> (Employee Id: <b>{{employeeId}}</b>) as <b>{{newReportingHead}}</b>
subjectMail= Request To Update Reporting Head

spring.main.allow-bean-definition-overriding=true

spring.devtools.restart.enabled = true

# updates
excelHeaderRowIndex = 0
excelDatesColumnIndex = 6
excelStatusColumnIndex = 5
excelCellLineBreakCharacterLength = 50
pbiTypeIndex = 0
descriptionIndex = 1
resourceIndex = 6
headerIndicator = Headers
resourceLeave = leaves
cronExpression = 0 0 2 * * ?
resourcePoolCronExpression = 0 0 2 * * ? 
reminderSubjectMail = Remainder to Update Reporting Head
reminderMailTemplateWithCurrentReportingHead=<b>Change reporting head of <b>{{employeeName}}</b> (Employee Id: <b>{{employeeId}}</b>) from <b>{{currentReportingHead}}</b> to <b>{{newReportingHead}}</b>
reminderMailTemplateWithoutCurrentReportingHead=<b>Change reporting head of <b>{{employeeName}}</b> (Employee Id: <b>{{employeeId}}</b>) as <b>{{newReportingHead}}</b>


# Swagger configuration
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.config-url=/project_tracker/openapi/swagger-config
springdoc.swagger-ui.url=/project_tracker/openapi
springdoc.api-docs.path=/openapi


debug=true
management.endpoints.web.exposure.include=beans